# Generated by Django 5.2.6 on 2025-11-29 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_category_women_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Известные женщины', 'verbose_name_plural': 'Известные женщины'},
        ),
        migrations.RenameField(
            model_name='women',
            old_name='pthoto',
            new_name='photo',
        ),
    ]
